#:kivy 1.11.1
#:include force dclasses.kv
#:include force navigation.kv
#import tr __main__.tr

<ListMetTables>:
    BoxLayout:
        orientation: 'vertical'
        Navigation:
        MainLabel:
            text: 'List & find activities'
        KSpinner:
            id: compendiumlist
            font_name: 'Arial.ttf'
            text: str(app.listOfMetTables[0])
            values: app.listOfMetTables
