#:kivy 1.11.1
#:include force dclasses.kv

#import tr __main__.tr

<Navigation>:
    orientation: 'horizontal'
    canvas:
        Color:
            rgba: 255/255., 255/255., 255/255., 1
        Rectangle:
            pos: self.pos
            size: self.size
    KNavigationButton:
        text: 'Next screen'
        on_release: app.nextscreen()

    KNavigationButton:
        text: 'Previous screen'
        on_release: app.previousscreen()